version: '3.3'

services:
  watchyourlan:
    image: aceberg/watchyourlan:latest
    container_name: watchyourlan
    restart: unless-stopped
    network_mode: host  # Required for proper LAN scanning
    environment:
      - TZ=Europe/Paris  # Change to your timezone
    volumes:
      - ./watchyourlan_data:/data
    cap_add:
      - NET_RAW  # Required for ARP scanning
      - NET_ADMIN

volumes:
  watchyourlan_data:
