version: "3"
services:
  netalertx:
    container_name: netalertx
    image: "jokobsk/netalertx:latest"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./config:/home/pi/pialert/config
      - ./db:/home/pi/pialert/db
      - ./logs:/home/pi/pialert/front/log
    environment:
      - TZ=Europe/Madrid
      - PORT=20211
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
