version: '3.8'

services:
  asterisk:
    image: andrius/asterisk
    container_name: asterisk
    restart: always
    ports:
      - "5060:5060/udp"   # SIP UDP
      - "5060:5060/tcp"   # SIP TCP
      - "8088:8088/tcp"   # HTTP for ARI
      - "10000-10050:10000-10050/udp"  # RTP
    volumes:
      - ./config:/etc/asterisk
    environment:
      - TZ=UTC
