global:
  scrape_interval: 5s

scrape_configs:
#  - job_name: "prometheus"
#    static_configs:
#      - targets: ["localhost:9090"]

  - job_name: "windows-exporter"
    static_configs:
      - targets: ["192.168.200.32:9182"]

  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "192.168.200.240:9100"  # ubuntu-srv-240
          - "192.168.200.241:9100"  # ubuntu-srv-241
          - "192.168.200.242:9100"  # ubuntu-srv-242
          - "192.168.200.253:9100"  # SIEM-253
          - "192.168.200.254:9100"  # Gateway-254

  - job_name: "snmp_device"
    metrics_path: /snmp  # SNMP Exporter endpoint
    params:
      module: [sys_info]  # This must match a module in snmp.yml
    static_configs:
      - targets:
          - "10.1.10.1"  # IP of SNMP device
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__

############################

  - job_name: 'blackbox_ping'
    metrics_path: /probe
    params:
      module: [icmp]  # Choose the Blackbox module to use
    static_configs:
      - targets:
          - 8.8.8.8
          - 1.1.1.1
          - 192.168.200.1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # Blackbox Exporter's container name or IP

  - job_name: "ping_exporter"
    static_configs:
      - targets:
          - "192.168.200.154:9427"

  - job_name: "watch_your_lan"
#    metrics_path: '/metrics'
    static_configs:
      - targets:
          - "192.168.200.154:8840"








