version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472"  # Ensure Grafana runs as the correct user
    restart: unless-stopped
    ports:
      - "3000:3000"  # Map Grafana to port 3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Oran_2024  # Change this!
      - GF_PATHS_DATA=/var/lib/grafana
    volumes:
      - ./grafana-data:/var/lib/grafana  # Persistent storage

volumes:
  grafana-data:
    driver: local
